#Generated by Kickstart Configurator
#platform=AMD64 or Intel EM64T

#System language
lang en_US
#Language modules to install
langsupport en_US
#System keyboard
keyboard us
#System mouse
mouse
#System timezone
timezone Asia/Kolkata
#Root password
rootpw password
#Initial user
user naanal --fullname "naanal" --iscrypted --password $1$g49mfFat$N0AB3sCRwIz/g0Xsoixl1.
#Reboot after installation
reboot
#Use text mode install
text
#Install OS instead of upgrade
install
#Use CDROM installation media
cdrom
#System bootloader configuration
bootloader --location=mbr 
#Clear the Master Boot Record
zerombr yes
#Partition clearing information
clearpart --all --initlabel 
#System authorization infomation
auth  --useshadow  --enablemd5 
#Network information
#network --bootproto=dhcp --device=eth0
#network --bootproto=dhcp --device=eth1
#Firewall configuration
firewall --disabled 
#Do not configure the X Window System
skipx

%packages
vim
openssh-server
vlan 
qemu-kvm 
libvirt-bin 
ubuntu-vm-builder 
bridge-utils 
cpu-checker
ntp
rabbitmq-server
mysql-server
python-mysqldb
keystone
glance
nova-api
nova-cert
nova-conductor
nova-consoleauth
nova-novncproxy
nova-scheduler 
python-novaclient 
nova-compute 
nova-console
neutron-server 
neutron-plugin-openvswitch 
neutron-plugin-openvswitch-agent 
neutron-common 
neutron-dhcp-agent 
neutron-l3-agent 
neutron-metadata-agent 
openvswitch-switch
openstack-dashboard
libapache2-mod-php5
php5-mysql
ceilometer-api 
ceilometer-collector 
ceilometer-agent-central 
ceilometer-agent-notification 
ceilometer-alarm-evaluator 
ceilometer-alarm-notifier 
python-ceilometerclient 
ceilometer-agent-compute
cinder-api 
cinder-scheduler 
lvm2 
tcm  
cinder-volume
upower 
dos2unix 
git

%post
echo "naanal-controller" > /etc/hostname
echo "127.0.1.1 naanal-controller" >> /etc/hosts


%end

%post --nochroot
cp -rf /cdrom/naanal/system/grub /target/etc/default/grub 
cp -rf /cdrom/naanal/system/sshd_config /target/etc/ssh/sshd_config
#rm -rf /target/lib/udev/rules.d/75-persistent-net-generator.rules
#rm -rf /target/etc/udev/rules.d/70-persistent-net.rules

%end

%post
update-grub


%end


